version: '3.4'

services:
  exporter:
    build:
      context: .
    image: redis-monitor
    ports:
      - 9292:9292
    volumes:
      - .:/app
    environment:
      - SIDEKIQ_REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:3.0.2
